config:
  send_anonymous_usage_stats: false

jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: '{{ env_var("HOST") }}'
      user: '{{ env_var("USERNAME") }}'
      password: '{{ env_var("PASSWORD") }}'
      port: '{{ env_var("PORT") | int }}'
      dbname: '{{ env_var("DATABASE") }}'
      schema: '{{ env_var("SCHEMA") }}'
      threads: 8

# prod and dev are the same for this demo.
    prod:
      type: postgres
      host: '{{ env_var("HOST") }}'
      user: '{{ env_var("USERNAME") }}'
      password: '{{ env_var("PASSWORD") }}'
      port: '{{ env_var("PORT") | int }}'
      dbname: '{{ env_var("DATABASE") }}'
      schema: '{{ env_var("SCHEMA") }}'
      threads: 8
