name: Manual dbt run force - prod

# sometimes you need to get a prod run through without running your tests
# use sparingly and your own risk

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Manually trigger a dev dbt run'
        required: false
        type: boolean

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DATABASE: ${{ secrets.DATABASE }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PORT: ${{ secrets.PORT }}
      SCHEMA: ${{ secrets.SCHEMA }}
    steps:
    - uses: "actions/checkout@main"

    - name: install requirements
      run: pip install -q -r requirements.txt

    - name: dbt deps
      run: |
        cd project_goes_here 
        dbt deps

    - name: dbt build
      run: |
        cd project_goes_here 
        dbt run --target prod

