name: Scheduled dbt run - prod

on:
  schedule:
  - cron: "10 10 * * *"
jobs:
  dbt_scheduled_run:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DATABASE: ${{ secrets.DATABASE }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PORT: ${{ secrets.PORT }}
      SCHEMA: ${{ secrets.SCHEMA }}
    steps:
    - uses: "actions/checkout@main"

    - name: install requirements
      run: pip install -q -r requirements.txt

    - name: dbt deps
      run: |
        cd project_goes_here 
        dbt deps

    - name: Get manifest.json from gh-pages branch
      run: |
        ./get_manifest.sh

    - name: dbt build
      run: |
        cd project_goes_here 
        if [ -f "prev_run_state/manifest.json" ]; then
          dbt build --full-refresh --fail-fast --select state:modified+ --state prev_run_state
          dbt docs generate
        else
          dbt build
          dbt docs generate
        fi

    - name: Push new documentation to GH Pages
      run: |
        ./save_and_publish_docs.sh
