name: Incremental run dbt on merge to Main

on:
  push:
    branches: ["main"]
  # leaving this for testing
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Manually trigger a dbt run'
        required: false
        type: boolean

jobs:
  dbt_run_on_merge_incremental:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DATABASE: ${{ secrets.DATABASE }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PORT: ${{ secrets.PORT }}
      SCHEMA: ${{ secrets.SCHEMA }}
    steps:
    - uses: "actions/checkout@v4"
      with:
        ref: gh-pages
    - uses: "actions/checkout@v4"

    - name: install requirements
      run: pip install -q -r requirements.txt

    - name: dbt deps
      run: |
        cd project_goes_here 
        dbt deps

    - name: Get manifest.json from gh-pages branch
      run: |
        ./get_manifest.sh

    - name: dbt build
      id: build
      if: ${{ always() && '!cancelled()' }}
      run: |
        cd project_goes_here 
        if [ -f "prev_run_state/manifest.json" ]; then
          dbt build --full-refresh --fail-fast --select state:modified+ --state prev_run_state
          dbt docs generate
        else
          dbt build
          dbt docs generate
        fi

    - name: Push new documentation to GH Pages
      if: ${{ (success() || failure()) && steps.build.conclusion == 'success' }}
      run: |
        ./save_and_publish_docs.sh
